# DB
quarkus.datasource.db-kind=oracle
quarkus.datasource.username=ADMIN
quarkus.datasource.password=Autoflex54321
quarkus.datasource.jdbc.url=jdbc:oracle:thin:@(description=(retry_count=20)(retry_delay=3)(address=(protocol=tcps)(port=1521)(host=adb.us-ashburn-1.oraclecloud.com))(connect_data=(service_name=gbbcacd490e728d_autoflex_medium.adb.oraclecloud.com))(security=(ssl_server_dn_match=yes)))
# Hibernate
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.sql-load-script=no-file
# HTTP
quarkus.http.port=8080
# CORS
quarkus.http.cors.enabled=true
quarkus.http.cors.origins=*
quarkus.http.cors.methods=GET,POST,PUT,PATCH,DELETE,OPTIONS
quarkus.http.cors.headers=accept,authorization,content-type,x-requested-with
# PATH API
quarkus.resteasy.path=/api